### PR TITLE
add mtfmk's new code

### PR DESCRIPTION
**Pull request by yumetodo**
ref:
- https://twitter.com/mtfmk/status/850524971432525825
- https://wandbox.org/permlink/aj8qmP72ExQOKVZx

### CODE REVIEW

**Comment by yumetodo** [comment]
```
generating inputs...done.
start benchmark mark:
calc_check_digit_yumetodo_kai_simd : test::pass:491[ms] (491253482[ns])
calc_check_digit_yumetodo_kai : test::pass:494[ms] (494111224[ns])
calc_check_digit_ryogaelbtn : test::pass:261[ms] (261891254[ns])
calc_check_digit_yumetodo : test::pass:382[ms] (382474749[ns])
calc_check_digit_ryogaelbtn2 : test::pass:1403[ms] (1403076578[ns])
calc_check_digit_yumetodo_original : test::pass:610[ms] (610699199[ns])
calc_check_digit_ysrken : test::pass:163[ms] (163490730[ns])
calc_check_digit_ysrken2 : test::pass:186[ms] (186377390[ns])
get_check_digit_ssse3 : test::pass:243[ms] (243234469[ns])
calc_check_digit_mtfmk : test::pass:214[ms] (214717968[ns])
calc_check_digit_mtfmk2 : test::pass:272[ms] (272984285[ns])
491253482,494111224,261891254,382474749,1403076578,610699199,163490730,186377390,243234469,214717968,272984285,
benchmark finish!
```

なんか遅いなぁ・・・。

```asm
00007FF74C0E2E80  sub         rsp,48h  
00007FF74C0E2E84  mov         rax,qword ptr [__security_cookie (07FF74C0ED010h)]  
00007FF74C0E2E8B  xor         rax,rsp  
00007FF74C0E2E8E  mov         qword ptr [rsp+30h],rax  
	if (mynumber.size() != 11) return 0xFF;
00007FF74C0E2E93  cmp         qword ptr [rcx+10h],0Bh  
00007FF74C0E2E98  je          calc_check_digit_mtfmk2+2Eh (07FF74C0E2EAEh)  
00007FF74C0E2E9A  mov         al,0FFh  
}
00007FF74C0E2E9C  mov         rcx,qword ptr [rsp+30h]  
00007FF74C0E2EA1  xor         rcx,rsp  
00007FF74C0E2EA4  call        __security_check_cookie (07FF74C0E5EE0h)  
00007FF74C0E2EA9  add         rsp,48h  
00007FF74C0E2EAD  ret  
	std::memcpy(array.data(), mynumber.c_str(), 11);
00007FF74C0E2EAE  cmp         qword ptr [rcx+18h],10h  
	alignas(16) std::array<char, 16> array{};
	array.fill('0');
00007FF74C0E2EB3  mov         rax,3030303030303030h  
00007FF74C0E2EBD  mov         qword ptr [array],rax  
00007FF74C0E2EC2  mov         qword ptr [rsp+28h],rax  
00007FF74C0E2EC7  mov         qword ptr [rsp+40h],rbx  
	std::memcpy(array.data(), mynumber.c_str(), 11);
00007FF74C0E2ECC  jb          calc_check_digit_mtfmk2+51h (07FF74C0E2ED1h)  
00007FF74C0E2ECE  mov         rcx,qword ptr [rcx]  
00007FF74C0E2ED1  movzx       eax,word ptr [rcx+8]  
00007FF74C0E2ED5  vmovsd      xmm0,qword ptr [rcx]  
00007FF74C0E2ED9  mov         word ptr [rsp+28h],ax  
00007FF74C0E2EDE  movzx       eax,byte ptr [rcx+0Ah]  
00007FF74C0E2EE2  mov         byte ptr [rsp+2Ah],al  
	static const __m128i c_zero = _mm_set1_epi8('0');
00007FF74C0E2EE6  mov         rax,qword ptr gs:[58h]  
00007FF74C0E2EEF  mov         ebx,4  
00007FF74C0E2EF4  vmovsd      qword ptr [array],xmm0  
00007FF74C0E2EFA  add         rbx,qword ptr [rax]  
00007FF74C0E2EFD  mov         eax,dword ptr [rbx]  
00007FF74C0E2EFF  cmp         dword ptr [c_zero+10h (07FF74C0EEFD0h)],eax  
00007FF74C0E2F05  jle         calc_check_digit_mtfmk2+0B8h (07FF74C0E2F38h)  
00007FF74C0E2F07  lea         rcx,[c_zero+10h (07FF74C0EEFD0h)]  
00007FF74C0E2F0E  call        _Init_thread_header (07FF74C0E6108h)  
00007FF74C0E2F13  cmp         dword ptr [c_zero+10h (07FF74C0EEFD0h)],0FFFFFFFFh  
00007FF74C0E2F1A  jne         calc_check_digit_mtfmk2+0B8h (07FF74C0E2F38h)  
	static const __m128i c_zero = _mm_set1_epi8('0');
00007FF74C0E2F1C  vmovdqu     xmm0,xmmword ptr [__xmm@30303030303030303030303030303030 (07FF74C0E9690h)]  
00007FF74C0E2F24  lea         rcx,[c_zero+10h (07FF74C0EEFD0h)]  
00007FF74C0E2F2B  vmovdqu     xmmword ptr [c_zero (07FF74C0EEFC0h)],xmm0  
00007FF74C0E2F33  call        _Init_thread_footer (07FF74C0E60A8h)  
	static const __m128i c_nine = _mm_set1_epi8('9');
00007FF74C0E2F38  mov         eax,dword ptr [rbx]  
00007FF74C0E2F3A  cmp         dword ptr [dist+4h (07FF74C0EDA64h)],eax  
00007FF74C0E2F40  jle         calc_check_digit_mtfmk2+0F3h (07FF74C0E2F73h)  
00007FF74C0E2F42  lea         rcx,[dist+4h (07FF74C0EDA64h)]  
00007FF74C0E2F49  call        _Init_thread_header (07FF74C0E6108h)  
00007FF74C0E2F4E  cmp         dword ptr [dist+4h (07FF74C0EDA64h)],0FFFFFFFFh  
00007FF74C0E2F55  jne         calc_check_digit_mtfmk2+0F3h (07FF74C0E2F73h)  
00007FF74C0E2F57  vmovdqu     xmm0,xmmword ptr [__xmm@39393939393939393939393939393939 (07FF74C0E96A0h)]  
00007FF74C0E2F5F  lea         rcx,[dist+4h (07FF74C0EDA64h)]  
00007FF74C0E2F66  vmovdqu     xmmword ptr [c_nine (07FF74C0EDA30h)],xmm0  
00007FF74C0E2F6E  call        _Init_thread_footer (07FF74C0E60A8h)  
	static const __m128i q_n0 = _mm_setr_epi16(6, 5, 4, 3, 2, 7, 6, 5);
00007FF74C0E2F73  mov         eax,dword ptr [rbx]  
00007FF74C0E2F75  cmp         dword ptr [c_nine+10h (07FF74C0EDA40h)],eax  
00007FF74C0E2F7B  jle         calc_check_digit_mtfmk2+12Eh (07FF74C0E2FAEh)  
00007FF74C0E2F7D  lea         rcx,[c_nine+10h (07FF74C0EDA40h)]  
00007FF74C0E2F84  call        _Init_thread_header (07FF74C0E6108h)  
00007FF74C0E2F89  cmp         dword ptr [c_nine+10h (07FF74C0EDA40h)],0FFFFFFFFh  
00007FF74C0E2F90  jne         calc_check_digit_mtfmk2+12Eh (07FF74C0E2FAEh)  
00007FF74C0E2F92  vmovdqu     xmm0,xmmword ptr [__xmm@00050006000700020003000400050006 (07FF74C0E9670h)]  
00007FF74C0E2F9A  lea         rcx,[c_nine+10h (07FF74C0EDA40h)]  
00007FF74C0E2FA1  vmovdqu     xmmword ptr [q_n0 (07FF74C0ED9F0h)],xmm0  
00007FF74C0E2FA9  call        _Init_thread_footer (07FF74C0E60A8h)  
	static const __m128i q_n1 = _mm_setr_epi16(4, 3, 2, 0, 0, 0, 0, 0);
00007FF74C0E2FAE  mov         eax,dword ptr [rbx]  
00007FF74C0E2FB0  cmp         dword ptr [q_n0+10h (07FF74C0EDA00h)],eax  
00007FF74C0E2FB6  mov         rbx,qword ptr [rsp+40h]  
00007FF74C0E2FBB  jle         calc_check_digit_mtfmk2+16Eh (07FF74C0E2FEEh)  
00007FF74C0E2FBD  lea         rcx,[q_n0+10h (07FF74C0EDA00h)]  
00007FF74C0E2FC4  call        _Init_thread_header (07FF74C0E6108h)  
00007FF74C0E2FC9  cmp         dword ptr [q_n0+10h (07FF74C0EDA00h)],0FFFFFFFFh  
00007FF74C0E2FD0  jne         calc_check_digit_mtfmk2+16Eh (07FF74C0E2FEEh)  
00007FF74C0E2FD2  vmovdqu     xmm0,xmmword ptr [__xmm@00000000000000000000000200030004 (07FF74C0E9650h)]  
00007FF74C0E2FDA  lea         rcx,[q_n0+10h (07FF74C0EDA00h)]  
00007FF74C0E2FE1  vmovdqu     xmmword ptr [q_n1 (07FF74C0EDA50h)],xmm0  
00007FF74C0E2FE9  call        _Init_thread_footer (07FF74C0E60A8h)  

	__m128i p_n0 = _mm_load_si128(reinterpret_cast<__m128i*>(array.data()));
00007FF74C0E2FEE  vmovdqu     xmm3,xmmword ptr [array]  
	if (!validate(p_n0, c_zero, c_nine)) {
00007FF74C0E2FF4  vmovdqu     xmm4,xmmword ptr [c_zero (07FF74C0EEFC0h)]  
00007FF74C0E2FFC  vpcmpgtb    xmm1,xmm3,xmmword ptr [c_nine (07FF74C0EDA30h)]  
00007FF74C0E3004  vpcmpgtb    xmm0,xmm4,xmm3  
00007FF74C0E3008  vpor        xmm1,xmm1,xmm0  
00007FF74C0E300C  vpcmpeqd    xmm2,xmm3,xmm3  
00007FF74C0E3010  vptest      xmm1,xmm2  
00007FF74C0E3015  jne         calc_check_digit_mtfmk2+1Ah (07FF74C0E2E9Ah)  
		return 0xFF;
	}

	p_n0 = _mm_subs_epu8(p_n0, c_zero);
00007FF74C0E301B  vpsubusb    xmm2,xmm3,xmm4  
00007FF74C0E301F  vpxor       xmm1,xmm1,xmm1  
	const __m128i zero = _mm_setzero_si128();
	__m128i p_n1 = _mm_unpackhi_epi8(p_n0, zero);
00007FF74C0E3023  vpunpckhbw  xmm0,xmm2,xmm1  
	p_n0 = _mm_unpacklo_epi8(p_n0, zero);
	__m128i sum = _mm_add_epi32(_mm_madd_epi16(p_n0, q_n0), _mm_madd_epi16(p_n1, q_n1));
00007FF74C0E3027  vpmaddwd    xmm3,xmm0,xmmword ptr [q_n1 (07FF74C0EDA50h)]  
00007FF74C0E302F  vpunpcklbw  xmm1,xmm2,xmm1  
00007FF74C0E3033  vpmaddwd    xmm2,xmm1,xmmword ptr [q_n0 (07FF74C0ED9F0h)]  
00007FF74C0E303B  vpaddd      xmm4,xmm3,xmm2  
	sum = _mm_add_epi32(sum, _mm_srli_si128(sum, 8));
00007FF74C0E303F  vpsrldq     xmm0,xmm4,8  
00007FF74C0E3044  vpaddd      xmm2,xmm0,xmm4  
	sum = _mm_add_epi32(sum, _mm_srli_si128(sum, 4));
00007FF74C0E3048  vpsrldq     xmm1,xmm2,4  
00007FF74C0E304D  vpaddd      xmm0,xmm1,xmm2  

	int ret = 11 - _mm_cvtsi128_si32(sum) % 11;
00007FF74C0E3051  vmovd       ecx,xmm0  
00007FF74C0E3055  mov         eax,2E8BA2E9h  
00007FF74C0E305A  imul        ecx  
00007FF74C0E305C  sar         edx,1  
00007FF74C0E305E  mov         eax,edx  
00007FF74C0E3060  shr         eax,1Fh  
00007FF74C0E3063  add         edx,eax  
00007FF74C0E3065  imul        eax,edx,0Bh  
00007FF74C0E3068  sub         ecx,eax  
00007FF74C0E306A  mov         eax,0Bh  
00007FF74C0E306F  sub         eax,ecx  
	return static_cast<uint8_t>(ret > 9 ? 0 : ret);
00007FF74C0E3071  xor         ecx,ecx  
00007FF74C0E3073  cmp         eax,9  
00007FF74C0E3076  cmovg       eax,ecx  
}
00007FF74C0E3079  mov         rcx,qword ptr [rsp+30h]  
00007FF74C0E307E  xor         rcx,rsp  
00007FF74C0E3081  call        __security_check_cookie (07FF74C0E5EE0h)  
00007FF74C0E3086  add         rsp,48h  
00007FF74C0E308A  ret  
```

**Comment by yumetodo** [comment]
static constをstaticにしたらもうすこしジャンプ命令が少ないものになったけど実行速度大差ないなぁ・・・

```
generating inputs...done.
start benchmark mark:
calc_check_digit_yumetodo_kai_simd : test::pass:496[ms] (496198491[ns])
calc_check_digit_yumetodo_kai : test::pass:496[ms] (496819940[ns])
calc_check_digit_ryogaelbtn : test::pass:267[ms] (267782040[ns])
calc_check_digit_yumetodo : test::pass:383[ms] (383458247[ns])
calc_check_digit_ryogaelbtn2 : test::pass:1410[ms] (1410924467[ns])
calc_check_digit_yumetodo_original : test::pass:602[ms] (602635194[ns])
calc_check_digit_ysrken : test::pass:163[ms] (163564004[ns])
calc_check_digit_ysrken2 : test::pass:190[ms] (190701258[ns])
get_check_digit_ssse3 : test::pass:236[ms] (236179624[ns])
calc_check_digit_mtfmk : test::pass:213[ms] (213204228[ns])
calc_check_digit_mtfmk2 : test::pass:275[ms] (275329716[ns])
496198491,496819940,267782040,383458247,1410924467,602635194,163564004,190701258,236179624,213204228,275329716,
benchmark finish!
```

```asm
00007FF7ED672E80  sub         rsp,28h  
00007FF7ED672E84  mov         rax,qword ptr [__security_cookie (07FF7ED67D010h)]  
00007FF7ED672E8B  xor         rax,rsp  
00007FF7ED672E8E  mov         qword ptr [rsp+10h],rax  
	if (mynumber.size() != 11) return 0xFF;
00007FF7ED672E93  cmp         qword ptr [rcx+10h],0Bh  
00007FF7ED672E98  je          calc_check_digit_mtfmk2+2Eh (07FF7ED672EAEh)  
00007FF7ED672E9A  mov         al,0FFh  
}
00007FF7ED672E9C  mov         rcx,qword ptr [rsp+10h]  
00007FF7ED672EA1  xor         rcx,rsp  
00007FF7ED672EA4  call        __security_check_cookie (07FF7ED675DD0h)  
00007FF7ED672EA9  add         rsp,28h  
00007FF7ED672EAD  ret  
	std::memcpy(array.data(), mynumber.c_str(), 11);
00007FF7ED672EAE  cmp         qword ptr [rcx+18h],10h  
	alignas(16) std::array<char, 16> array{};
	array.fill('0');
00007FF7ED672EB3  mov         rax,3030303030303030h  
00007FF7ED672EBD  mov         qword ptr [rsp],rax  
00007FF7ED672EC1  mov         qword ptr [rsp+8],rax  
	std::memcpy(array.data(), mynumber.c_str(), 11);
00007FF7ED672EC6  jb          calc_check_digit_mtfmk2+4Bh (07FF7ED672ECBh)  
00007FF7ED672EC8  mov         rcx,qword ptr [rcx]  
00007FF7ED672ECB  movzx       eax,word ptr [rcx+8]  
	std::memcpy(array.data(), mynumber.c_str(), 11);
00007FF7ED672ECF  vmovsd      xmm0,qword ptr [rcx]  
	const __m128i c_zero = _mm_set1_epi8('0');
00007FF7ED672ED3  vmovdqu     xmm5,xmmword ptr [__xmm@30303030303030303030303030303030 (07FF7ED679690h)]  
00007FF7ED672EDB  mov         word ptr [rsp+8],ax  
00007FF7ED672EE0  movzx       eax,byte ptr [rcx+0Ah]  
00007FF7ED672EE4  mov         byte ptr [rsp+0Ah],al  
00007FF7ED672EE8  vmovdqu     xmm4,xmmword ptr [rsp]  
00007FF7ED672EED  vmovsd      xmm4,xmm4,xmm0  
	const __m128i c_nine = _mm_set1_epi8('9');
	const __m128i q_n0 = _mm_setr_epi16(6, 5, 4, 3, 2, 7, 6, 5);
	const __m128i q_n1 = _mm_setr_epi16(4, 3, 2, 0, 0, 0, 0, 0);

	__m128i p_n0 = _mm_load_si128(reinterpret_cast<__m128i*>(array.data()));
	if (!validate(p_n0, c_zero, c_nine)) {
00007FF7ED672EF1  vpcmpgtb    xmm2,xmm4,xmmword ptr [__xmm@39393939393939393939393939393939 (07FF7ED6796A0h)]  
00007FF7ED672EF9  vpcmpgtb    xmm1,xmm5,xmm4  
00007FF7ED672EFD  vpor        xmm2,xmm2,xmm1  
00007FF7ED672F01  vpcmpeqd    xmm3,xmm4,xmm4  
00007FF7ED672F05  vptest      xmm2,xmm3  
00007FF7ED672F0A  jne         calc_check_digit_mtfmk2+1Ah (07FF7ED672E9Ah)  
		return 0xFF;
	}

	p_n0 = _mm_subs_epu8(p_n0, c_zero);
00007FF7ED672F0C  vpxor       xmm2,xmm2,xmm2  
00007FF7ED672F10  vpsubusb    xmm4,xmm4,xmm5  
	const __m128i zero = _mm_setzero_si128();
	__m128i p_n1 = _mm_unpackhi_epi8(p_n0, zero);
	p_n0 = _mm_unpacklo_epi8(p_n0, zero);
00007FF7ED672F14  vpunpcklbw  xmm1,xmm4,xmm2  
	__m128i sum = _mm_add_epi32(_mm_madd_epi16(p_n0, q_n0), _mm_madd_epi16(p_n1, q_n1));
00007FF7ED672F18  vpmaddwd    xmm3,xmm1,xmmword ptr [__xmm@00050006000700020003000400050006 (07FF7ED679670h)]  
00007FF7ED672F20  vpunpckhbw  xmm2,xmm4,xmm2  
00007FF7ED672F24  vpmaddwd    xmm0,xmm2,xmmword ptr [__xmm@00000000000000000000000200030004 (07FF7ED679650h)]  
00007FF7ED672F2C  vpaddd      xmm3,xmm3,xmm0  
	sum = _mm_add_epi32(sum, _mm_srli_si128(sum, 8));
00007FF7ED672F30  vpsrldq     xmm1,xmm3,8  
00007FF7ED672F35  vpaddd      xmm2,xmm1,xmm3  
	sum = _mm_add_epi32(sum, _mm_srli_si128(sum, 4));
00007FF7ED672F39  vpsrldq     xmm0,xmm2,4  
00007FF7ED672F3E  vpaddd      xmm1,xmm0,xmm2  

	int ret = 11 - _mm_cvtsi128_si32(sum) % 11;
00007FF7ED672F42  vmovd       ecx,xmm1  
00007FF7ED672F46  mov         eax,2E8BA2E9h  
00007FF7ED672F4B  imul        ecx  
00007FF7ED672F4D  sar         edx,1  
00007FF7ED672F4F  mov         eax,edx  
00007FF7ED672F51  shr         eax,1Fh  
00007FF7ED672F54  add         edx,eax  
00007FF7ED672F56  imul        eax,edx,0Bh  
00007FF7ED672F59  sub         ecx,eax  
00007FF7ED672F5B  mov         eax,0Bh  
00007FF7ED672F60  sub         eax,ecx  
	return static_cast<uint8_t>(ret > 9 ? 0 : ret);
00007FF7ED672F62  xor         ecx,ecx  
00007FF7ED672F64  cmp         eax,9  
00007FF7ED672F67  cmovg       eax,ecx  
}
00007FF7ED672F6A  mov         rcx,qword ptr [rsp+10h]  
00007FF7ED672F6F  xor         rcx,rsp  
00007FF7ED672F72  call        __security_check_cookie (07FF7ED675DD0h)  
00007FF7ED672F77  add         rsp,28h  
00007FF7ED672F7B  ret  
```

**Comment by MaverickTse** [comment]
i guess it is the extra memory allocation and memcpy that slow things a bit

**Comment by yumetodo** [comment]
@MaverickTse うーん
staticあり版
image
staticなし版
image

**Comment by MaverickTse** [comment]
why set1_epi8 sometimes take 0.1% but other time 0.9%??? is this performance profile really meaningful?

**Pull request merged**
